version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: corebank
      POSTGRES_HOST: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./logs:/app/logs

  app:
    restart: always
    build: .
    ports:
      - "10090:8000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: corebank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      JWT_SECRET_KEY: tu_clave_secreta_desarrollo
      ENCRYPTION_KEY: tu_clave_segura_aqui
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_EMAIL: tu_email
      SMTP_PASSWORD: email_password

volumes:
  pgdata:
